package com.atiurin.ultron.core.uiautomator

import com.atiurin.ultron.core.common.UltronOperationType

enum class UiAutomatorActionType :
        UltronOperationType {
    CLICK, CLICK_AND_WAIT_FOR_NEW_WINDOW, CLICK_TOP_LEFT, CLICK_BOTTOM_RIGHT,
    LONG_CLICK, LONG_CLICK_BOTTOM_RIGHT,  LONG_CLICK_TOP_LEFT,
    DRAG, FLING, PINCH_CLOSE, PINCH_OPEN, PINCH_OUT, PINCH_IN,
    ADD_TEXT, REPLACE_TEXT, CLEAR_TEXT, GET_TEXT, LEGACY_SET_TEXT,
    GET_APPLICATION_PACKAGE, GET_BOUNDS, GET_VISIBLE_BOUNDS, GET_VISIBLE_CENTER, GET_CLASS_NAME, GET_CONTENT_DESCRIPTION, GET_RESOURCE_NAME,
    GET_PARENT, GET_CHILDREN, GET_CHILD, GET_CHILD_COUNT, GET_FROM_PARENT, FIND_OBJECT, FIND_OBJECTS,
    SWIPE, SWIPE_LEFT, SWIPE_RIGHT, SWIPE_UP, SWIPE_DOWN, SCROLL, PERFORM
}